//electric Moves
      private function CreateElectricMoves() : void
      {
         var _loc1_:BaseMinionMove = null;
         var _loc2_:Array = null;
         var _loc3_:Array = null;
         var _loc4_:Array = null;
         this.m_currMinionMoveClass = MinionMoveClasses.charge_blast;
         this.m_currFirstMinionMoveID = MinionMoveID.charge_blast_t1;
         this.m_currMoveIconName = "moveIcon_chargeBlast";
         this.m_currMinionMoveVisuals = MinionVisualMoveID.VISUALS_SameAsClass;
         _loc1_ = this.old_EnergyCM(0,"Charge Blast",5,50,5);
         _loc1_ = this.old_EnergyCM(1,"Charge Blast  lv.2",5,75,9);
         _loc1_ = this.old_EnergyCM(2,"Charge Blast  lv.3",5,100,20);
         _loc1_ = this.old_EnergyCM(3,"Charge Blast  lv.4",5,125,27);
         _loc1_ = this.old_EnergyCM(4,"Electrocution",5,200,40);
         this.m_currMinionMoveClass = MinionMoveClasses.batch_bolt;
         this.m_currFirstMinionMoveID = MinionMoveID.batch_bolt_t1;
         this.m_currMoveIconName = "moveIcon_batchBolt";
         this.m_currMinionMoveVisuals = MinionVisualMoveID.VISUALS_SameAsClass;
         _loc1_ = this.old_EnergyCM(0,"Batch Bolt",1,29,10,5);
         _loc1_.m_isThereABufferBetweenVisualMovesOnMultipleEnemies = false;
         _loc1_ = this.old_EnergyCM(1,"Batch Bolt  lv.2",1,44,15,5);
         _loc1_.m_isThereABufferBetweenVisualMovesOnMultipleEnemies = false;
         _loc1_ = this.old_EnergyCM(2,"Batch Bolt  lv.3",1,59,30,5);
         _loc1_.m_isThereABufferBetweenVisualMovesOnMultipleEnemies = false;
         _loc1_ = this.old_EnergyCM(3,"Batch Bolt  lv.4",1,74,40,5);
         _loc1_.m_isThereABufferBetweenVisualMovesOnMultipleEnemies = false;
         _loc1_ = this.old_EnergyCM(4,"Bolt Storm",1,99,65,5);
         _loc1_.m_isThereABufferBetweenVisualMovesOnMultipleEnemies = false;
         this.m_currMinionMoveClass = MinionMoveClasses.spark;
         this.m_currFirstMinionMoveID = MinionMoveID.spark_t1;
         this.m_currMoveIconName = "moveIcon_spark";
         this.m_currMinionMoveVisuals = MinionVisualMoveID.VISUALS_SameAsClass;
         _loc1_ = this.old_EnergyCM(0,"Spark",25,10,5);
         _loc1_ = this.old_EnergyCM(1,"Spark  lv.2",35,15,9);
         _loc1_ = this.old_EnergyCM(2,"Spark  lv.3",40,20,20);
         _loc1_ = this.old_EnergyCM(3,"Spark  lv.4",50,25,27);
         _loc1_ = this.old_EnergyCM(4,"Boom Crash",90,40,40,1,90);
         this.m_currMinionMoveClass = MinionMoveClasses.charge_pass;
         this.m_currFirstMinionMoveID = MinionMoveID.charge_pass_t1;
         this.m_currMoveIconName = "moveIcon_chargePass";
         this.m_currMinionMoveVisuals = MinionVisualMoveID.VISUALS_SameAsClass;
         _loc1_ = this.old_EnergyCM(0,"Charge Pass",20,5,5,1,70);
         _loc1_.m_doesBuffSelf = true;
         _loc1_.AddStatToBuff(StatType.STAT_SPEED);
         _loc1_.m_stagesOfStatTypeToBuff = 1;
         _loc1_ = this.old_EnergyCM(1,"Charge Pass  lv.2",30,10,9,1,70);
         _loc1_.m_doesBuffSelf = true;
         _loc1_.AddStatToBuff(StatType.STAT_SPEED);
         _loc1_.m_stagesOfStatTypeToBuff = 1;
         _loc1_ = this.old_EnergyCM(2,"Charge Pass  lv.3",35,15,20,1,70);
         _loc1_.m_doesBuffSelf = true;
         _loc1_.AddStatToBuff(StatType.STAT_SPEED);
         _loc1_.m_stagesOfStatTypeToBuff = 1;
         _loc1_ = this.old_EnergyCM(3,"Charge Pass  lv.4",40,20,27,1,70);
         _loc1_.m_doesBuffSelf = true;
         _loc1_.AddStatToBuff(StatType.STAT_SPEED);
         _loc1_.m_stagesOfStatTypeToBuff = 1;
         _loc1_ = this.old_EnergyCM(4,"Triple Chargebolt",40,30,45,1,50);
         _loc1_.m_doesBuffSelf = true;
         _loc1_.AddStatToBuff(StatType.STAT_SPEED);
         _loc1_.m_stagesOfStatTypeToBuff = 1;
         this.m_currMinionMoveClass = MinionMoveClasses.static_pummel;
         this.m_currFirstMinionMoveID = MinionMoveID.static_pummel_t1;
         this.m_currMoveIconName = "moveIcon_staticPummel";
         this.m_currMinionMoveVisuals = MinionVisualMoveID.VISUALS_SameAsClass;
         _loc1_ = this.old_EnergyCM(0,"Static Pummel",20,0,3,1,100,0,10);
         _loc1_ = this.old_EnergyCM(1,"Static Pummel  lv.2",25,0,7,1,100,0,20);
         _loc1_ = this.old_EnergyCM(2,"Static Pummel  lv.3",30,0,15,1,100,0,30);
         _loc1_ = this.old_EnergyCM(3,"Static Pummel  lv.4",35,0,20,1,100,0,40);
         _loc1_ = this.old_EnergyCM(4,"Stun Blast",40,0,50,1,100,0,100);
         _loc2_ = new Array(7,12,25,32,50);
         _loc3_ = new Array(1,1,1,1,1);
         _loc4_ = new Array(29,44,59,74,99);
         _loc1_ = this.CreateMove("Thunderstorm",_loc2_[0],MinionMoveClasses.thunderstorm,MinionMoveID.thunderstorm_t1,"moveIcon_thunderstorm",MinionType.TYPE_ENERGY,MinionVisualMoveID.VISUALS_SameAsClass);
         _loc1_.m_damage = _loc3_[0];
         _loc1_.m_additionalRandomDamage = _loc4_[0];
         _loc1_.m_enemiesItHits = 3;
         _loc1_.m_hitsRandomTargets = true;
         _loc1_.m_isThereABufferBetweenVisualMovesOnMultipleEnemies = false;
         _loc1_ = this.CopyMove(_loc1_,_loc2_[1]);
         _loc1_.m_damage = _loc3_[1];
         _loc1_.m_additionalRandomDamage = _loc4_[1];
         _loc1_ = this.CopyMove(_loc1_,_loc2_[2]);
         _loc1_.m_damage = _loc3_[2];
         _loc1_.m_additionalRandomDamage = _loc4_[2];
         _loc1_ = this.CopyMove(_loc1_,_loc2_[3]);
         _loc1_.m_damage = _loc3_[3];
         _loc1_.m_additionalRandomDamage = _loc4_[3];
         _loc1_ = this.CopyMove(_loc1_,_loc2_[4],"Cloudburst");
         _loc1_.m_damage = _loc3_[4];
         _loc1_.m_additionalRandomDamage = _loc4_[4];
         _loc2_ = new Array(20,35,50,70,100);
         _loc3_ = new Array(1,1,1,1,50);
         _loc4_ = new Array(99,174,249,349,450);
         _loc1_ = this.CreateMove("Overload",_loc2_[0],MinionMoveClasses.overload,MinionMoveID.overload_t1,"moveIcon_overload",MinionType.TYPE_ENERGY,MinionVisualMoveID.VISUALS_SameAsClass);
         _loc1_.m_damage = _loc3_[0];
         _loc1_.m_additionalRandomDamage = _loc4_[0];
         _loc1_.m_accuracy = 90;
         _loc1_.m_moveCoolDownTime = 1;
         _loc1_ = this.CopyMove(_loc1_,_loc2_[1]);
         _loc1_.m_damage = _loc3_[1];
         _loc1_.m_additionalRandomDamage = _loc4_[1];
         _loc1_ = this.CopyMove(_loc1_,_loc2_[2]);
         _loc1_.m_damage = _loc3_[2];
         _loc1_.m_additionalRandomDamage = _loc4_[2];
         _loc1_ = this.CopyMove(_loc1_,_loc2_[3]);
         _loc1_.m_damage = _loc3_[3];
         _loc1_.m_additionalRandomDamage = _loc4_[3];
         _loc1_ = this.CopyMove(_loc1_,_loc2_[4],"Cern Reaction");
         _loc1_.m_damage = _loc3_[4];
         _loc1_.m_additionalRandomDamage = _loc4_[4];
         _loc1_.m_accuracy = 100;
         _loc1_.m_moveCoolDownTime = 3;
         _loc2_ = new Array(5,9,20,27,40);
         _loc3_ = new Array(35,45,50,70,100);
         _loc4_ = new Array(10,15,20,25,50);
         _loc1_ = this.CreateMove("Blinding Jolt",_loc2_[0],MinionMoveClasses.blinding_jolt,MinionMoveID.blinding_jolt_t1,"moveIcon_blindingJolt",MinionType.TYPE_ENERGY,MinionVisualMoveID.VISUALS_SameAsClass);
         _loc1_.m_damage = _loc3_[0];
         _loc1_.m_additionalRandomDamage = _loc4_[0];
         _loc1_.m_accuracy = 80;
         _loc1_ = this.CopyMove(_loc1_,_loc2_[1]);
         _loc1_.m_damage = _loc3_[1];
         _loc1_.m_additionalRandomDamage = _loc4_[1];
         _loc1_.m_stunChance = 5;
         _loc1_ = this.CopyMove(_loc1_,_loc2_[2]);
         _loc1_.m_damage = _loc3_[2];
         _loc1_.m_additionalRandomDamage = _loc4_[2];
         _loc1_ = this.CopyMove(_loc1_,_loc2_[3]);
         _loc1_.m_damage = _loc3_[3];
         _loc1_.m_additionalRandomDamage = _loc4_[3];
         _loc1_ = this.CopyMove(_loc1_,_loc2_[4],"Veiled Thunderjolt");
         _loc1_.m_damage = _loc3_[4];
         _loc1_.m_additionalRandomDamage = _loc4_[4];
         _loc1_.m_stunChance = 10;
         _loc1_.m_moveCoolDownTime = 2;
         _loc1_ = this.CreateMove("Stun",35,MinionMoveClasses.stun,MinionMoveID.stun_t1,"moveIcon_stun",MinionType.TYPE_ENERGY,MinionVisualMoveID.VISUALS_SameAsClass);
         _loc1_.m_stunChance = 100;
      }



//electric-specific move creation
private function old_EnergyCM(param1:int, param2:String, param3:int, param4:int, param5:int, param6:int = 1, param7:int = 100, param8:int = 0, param9:int = 0) : BaseMinionMove
{
   var _loc10_:BaseMinionMove = null;
   (_loc10_ = new BaseMinionMove()).m_moveID = this.m_currFirstMinionMoveID + param1;
   _loc10_.m_moveClass = this.m_currMinionMoveClass;
   _loc10_.m_moveTier = param1;
   _loc10_.m_enemiesItHits = param6;
   _loc10_.m_accuracy = param7;
   _loc10_.m_visualMoveID = this.m_currMinionMoveVisuals;
   _loc10_.m_visualDOTMoveID = this.m_currMinionDOTMoveVisuals;
   _loc10_.m_moveIcon = this.m_currMoveIconName;
   _loc10_.m_moveType = MinionType.TYPE_ENERGY;
   _loc10_.m_moveName = param2;
   _loc10_.m_damage = param3;
   _loc10_.m_additionalRandomDamage = param4;
   _loc10_.m_energyUsed = param5;
   _loc10_.m_moveCoolDownTime = param8;
   _loc10_.m_stunChance = param9;
   this.m_allMoves[_loc10_.m_moveID] = _loc10_;
   return _loc10_;
}